# Generated by Django 4.2 on 2024-04-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('MaterialId', models.AutoField(primary_key=True, serialize=False)),
                ('MaterialName', models.CharField(max_length=500)),
                ('Cost', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('SellerId', models.AutoField(primary_key=True, serialize=False)),
                ('SellerName', models.CharField(max_length=500)),
                ('Material', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
